name: build

on:
  workflow_call:
    inputs:
      skip_create_ami:
        required: true
        type: boolean

permissions:
  id-token: write
  contents: read

defaults:
  run:
    shell: bash

jobs:
  compute-matrix:
    runs-on: ubuntu-latest
    outputs:
      MATRIX: ${{ steps.compute-matrix.outputs.MATRIX }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Compute matrix
        id: compute-matrix
        run: |
          MATRIX=$(ci/compute-matrix.sh)
          echo "MATRIX=${MATRIX}" | tee --append ${GITHUB_OUTPUT}
  build:
    needs: compute-matrix
    strategy:
      matrix: ${{ fromJSON(needs.compute-matrix.outputs.MATRIX) }}
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ vars.VM_IMAGES_AWS_ROLE_ARN }}
          aws-region: ${{ vars.AWS_REGION }}
      - uses: actions/checkout@v4
      - name: Compute matrix ID
        run: |
          MATRIX_ID=$(ci/compute-matrix-id.sh)
          echo "MATRIX_ID=${MATRIX_ID}" | tee --append "${GITHUB_ENV}"
        env:
          ARCH: ${{ matrix.ARCH }}
          DRIVER_VERSION: ${{ matrix.DRIVER_VERSION }}
          OS: ${{ matrix.OS }}
          RUNNER_VERSION: ${{ matrix.RUNNER_VERSION }}
        # The `exec` command is used to help forward signals to the child process.
        # This helps ensure Packer's AWS resources get removed when the job is cancelled.
      - name: Build image
        run: |
          packer init .
          exec packer build \
            -only="${PACKER_SOURCE}*" \
            -var "arch=${ARCH}" \
            -var "driver_version=${DRIVER_VERSION}" \
            -var "gh_run_id=${GITHUB_RUN_ID}" \
            -var "os=${OS}" \
            -var "matrix_id=${MATRIX_ID}" \
            -var "runner_env=${RUNNER_ENV}" \
            -var "runner_version=${RUNNER_VERSION}" \
            -var "skip_create_ami=${SKIP_CREATE_AMI}" \
            .
        env:
          ARCH: ${{ matrix.ARCH }}
          DRIVER_VERSION: ${{ matrix.DRIVER_VERSION }}
          OS: ${{ matrix.OS }}
          PACKER_SOURCE: ${{ matrix.packer_source }}
          RUNNER_ENV: ${{ matrix.ENV }}
          RUNNER_VERSION: ${{ matrix.RUNNER_VERSION }}
          SKIP_CREATE_AMI: ${{ inputs.skip_create_ami }}
      - name: Clean Up Instance
        if: always()
        run: ci/clean-up-instance.sh
