name: build

on:
  workflow_call:
    inputs:
      skip_create_ami:
        required: true
        type: boolean

permissions:
  id-token: write
  contents: read

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        KUBERNETES_VERSION:
          - "1.24"
          - "1.25"
          - "1.26"
        DRIVER_VERSION:
          - "520.61.05"
          - "525.105.17"
    runs-on: ubuntu-latest
    container:
      image: hashicorp/packer:latest
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ vars.PACKER_AWS_ROLE_ARN }}
          aws-region: ${{ vars.AWS_REGION }}
      - uses: actions/checkout@v3
      - name: Install Ansible
        run: apk add ansible
      - name: Build image
        run: |
          packer init .
          packer build \
            -var "skip_create_ami=${{ inputs.skip_create_ami }}" \
            -var "kubernetes_version=${{ matrix.KUBERNETES_VERSION }}" \
            -var "driver_version=${{ matrix.DRIVER_VERSION }}" \
            .
