name: build

on:
  workflow_call:
    inputs:
      skip_create_ami:
        required: true
        type: boolean

jobs:
  build:
    strategy:
      matrix:
        KUBERNETES_VERSION:
          - "1.24"
        DRIVER_VERSION:
          - "520.61.05"
          - "525.85.12"
    runs-on: ubuntu-latest
    container:
      image: hashicorp/packer:latest
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.RAPIDSAI_GHA_PACKER_AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.RAPIDSAI_GHA_PACKER_AWS_SECRET_ACCESS_KEY }}
    steps:
      - uses: actions/checkout@v3
      - name: Install Ansible
        run: apk add ansible
      - name: Build image
        run: |
          packer init .
          packer build \
            -var "skip_create_ami=${{ inputs.skip_create_ami }}" \
            -var "kubernetes_version=${{ matrix.KUBERNETES_VERSION }}" \
            -var "driver_version=${{ matrix.DRIVER_VERSION }}" \
            .
