name: branch

on:
  push:
    branches:
      - main
      - deps-actions-runner-[0-9]*
      - test-**

permissions:
  id-token: write
  contents: read

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

jobs:
  build:
    uses: ./.github/workflows/build.yaml
    with:
      upload_artifacts: true
      branch_name: ${{ github.ref_name }}
    secrets: inherit
