name: prs

on:
  push:
    branches:
      - "pull-request/[0-9]+"

permissions:
  id-token: write
  contents: read

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

jobs:
  fmt:
    runs-on: ubuntu-latest
    container:
      image: hashicorp/packer:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Check Packer files formatting
        run: packer fmt -check -recursive .
  shellcheck:
    runs-on: ubuntu-latest
    container:
      image: koalaman/shellcheck-alpine:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run shellcheck on shell scripts
        run: find . -name "*.sh" | xargs -n 1 shellcheck --color=always
  gc:
    uses: ./.github/workflows/gc.yaml
    with:
      dry_run: true
    secrets: inherit
  build:
    uses: ./.github/workflows/build.yaml
    with:
      upload_artifacts: false
      branch_name: ${{ github.ref_name }}
    secrets: inherit
