name: prs

on:
  push:
    branches-ignore:
      - main

permissions:
  id-token: write
  contents: read

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

jobs:
  build:
    uses: ./.github/workflows/build.yaml
    with:
      skip_create_ami: true
    secrets: inherit
