name: prs

on:
  push:
    branches-ignore:
      - main

permissions:
  id-token: write
  contents: read

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

jobs:
  # TODO: update PR build job
  # build:
  #   uses: ./.github/workflows/build.yaml
  #   with:
  #     skip_create_ami: true
  #   secrets: inherit
  temp:
    runs-on: ubuntu-latest
    steps:
      - run: echo "temp job"
