name: prs

on:
  push:
    branches-ignore:
      - main

permissions:
  id-token: write
  contents: read

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

jobs:
  fmt:
    runs-on: ubuntu-latest
    container:
      image: hashicorp/packer:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Check Packer files formatting
        run: packer fmt -check -recursive .
  build:
    uses: ./.github/workflows/build.yaml
    with:
      skip_create_ami: true
    secrets: inherit
